name: master

on:
  push:
    branches: [ action ]

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: gradle
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Donwload Tmoe
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: cinit/TMoe
          workflow: push_ci.yml
          path: modules
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGN_KEYSTORE_BASE64 }} | base64 -d > keystore.jks
          ./gradlew :TMessagesProj:assemble
        env:
          KEYSTORE_PASS: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          ALIAS_NAME: ${{ secrets.SIGN_ALIAS }}
          ALIAS_PASS: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        # don't upload the artifacts if it's a pull request
        if: ${{ !github.event.pull_request }}
        with:
          path: 'app/build/outputs/apk/release/*.apk'
          name: QAuxiliary-release-${{ github.event.head_commit.id }}
